Feature to add a CSV file download route
ta-vivo/ta-vivo-api pull request #91
Opened 2023-06-16 02:24 UTC by bernestdev

### General
Added a new route to handle the download of CSV files

### Type

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Fix
- [x] Feature

### Describe the changes here (summarized)
- Added new route `/:id/logs/download` that returns a string and the header `Content-Type: text/csv`
- Added `es6` env to the `.eslintrc.json` file to allow support for extra es6 features including the ability to create promises with `new Promise()`
- Added `csv-stringify` library for converting arrays into a string CSV

2023-06-16 23:15 UTC, itsalb3rt requested changes

2023-06-16 23:15 UTC, itsalb3rt commented on src/controllers/CheckController.js
Great work! All works as expected. Only one thing, You can move the DB interaction of the `Checks` model to the `ChecksService` File, this is to keep the consistency. All the DB interactions are in services files and the controllers are only for HTTP handling and service delegation.

2023-06-16 23:15 UTC, itsalb3rt commented on src/services/CheckService.js
> +  static async getLogsCSV(logs) {
The comment about the DB interaction can move here. ☺️

2023-06-17 00:53 UTC, bernestdev commented
Thank you @itsalb3rt . I made the requested changes. Please let me know if this satisfies the request

2023-06-17 23:49 UTC, itsalb3rt approved these changes
Awesome, work perfect!

2023-06-17 23:50 UTC, merged